{"sections":[],"variants":[{"paths":["\/documentation\/digimecore\/syncerror\/init(from:)"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"Decodable.init(from:)","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":" ","kind":"text"},{"text":"decoder","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DigiMeCore\/documentation\/DigiMeCore","doc:\/\/DigiMeCore\/documentation\/DigiMeCore\/SyncError"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"init","modules":[{"name":"DigiMeCore"}],"title":"init(from:)","externalID":"s:10DigiMeCore9SyncErrorV4fromACs7Decoder_p_tKcfc","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"roleHeading":"Initializer","role":"symbol"},"identifier":{"url":"doc:\/\/DigiMeCore\/documentation\/DigiMeCore\/SyncError\/init(from:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DigiMeCore/documentation/DigiMeCore":{"type":"topic","kind":"symbol","title":"DigiMeCore","identifier":"doc:\/\/DigiMeCore\/documentation\/DigiMeCore","abstract":[],"url":"\/documentation\/digimecore","role":"collection"},"doc://DigiMeCore/documentation/DigiMeCore/SyncError":{"abstract":[{"type":"text","text":"Reason why connecting to source or importing data from source into userâ€™s library failed"}],"kind":"symbol","url":"\/documentation\/digimecore\/syncerror","identifier":"doc:\/\/DigiMeCore\/documentation\/DigiMeCore\/SyncError","title":"SyncError","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SyncError"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SyncError"}]},"doc://DigiMeCore/documentation/DigiMeCore/SyncError/init(from:)":{"abstract":[],"kind":"symbol","title":"init(from:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"url":"\/documentation\/digimecore\/syncerror\/init(from:)","identifier":"doc:\/\/DigiMeCore\/documentation\/DigiMeCore\/SyncError\/init(from:)","role":"symbol"}}}