{"abstract":[{"type":"text","text":"An error giving details of the reason synchronization failed."},{"text":" ","type":"text"},{"type":"text","text":"Only available for ‘partial’ synchronization state"}],"metadata":{"symbolKind":"property","modules":[{"name":"DigiMeCore"}],"role":"symbol","roleHeading":"Instance Property","externalID":"s:10DigiMeCore11SyncAccountV5errorAA0D5ErrorVSgvp","title":"error","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"error","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10DigiMeCore9SyncErrorV","text":"SyncError","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DigiMeCore\/documentation\/DigiMeCore","doc:\/\/DigiMeCore\/documentation\/DigiMeCore\/SyncAccount"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SyncError","preciseIdentifier":"s:10DigiMeCore9SyncErrorV","identifier":"doc:\/\/DigiMeCore\/documentation\/DigiMeCore\/SyncError"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DigiMeCore\/documentation\/DigiMeCore\/SyncAccount\/error"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/digimecore\/syncaccount\/error"]}],"sections":[],"references":{"doc://DigiMeCore/documentation/DigiMeCore/SyncAccount":{"title":"SyncAccount","abstract":[{"text":"Details of a source being synchronized","type":"text"}],"kind":"symbol","url":"\/documentation\/digimecore\/syncaccount","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SyncAccount"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SyncAccount"}],"identifier":"doc:\/\/DigiMeCore\/documentation\/DigiMeCore\/SyncAccount"},"doc://DigiMeCore/documentation/DigiMeCore/SyncAccount/error":{"title":"error","abstract":[{"text":"An error giving details of the reason synchronization failed.","type":"text"},{"text":" ","type":"text"},{"text":"Only available for ‘partial’ synchronization state","type":"text"}],"kind":"symbol","url":"\/documentation\/digimecore\/syncaccount\/error","type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10DigiMeCore9SyncErrorV","text":"SyncError"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/DigiMeCore\/documentation\/DigiMeCore\/SyncAccount\/error"},"doc://DigiMeCore/documentation/DigiMeCore":{"type":"topic","kind":"symbol","title":"DigiMeCore","identifier":"doc:\/\/DigiMeCore\/documentation\/DigiMeCore","abstract":[],"url":"\/documentation\/digimecore","role":"collection"},"doc://DigiMeCore/documentation/DigiMeCore/SyncError":{"abstract":[{"type":"text","text":"Reason why connecting to source or importing data from source into user’s library failed"}],"kind":"symbol","url":"\/documentation\/digimecore\/syncerror","identifier":"doc:\/\/DigiMeCore\/documentation\/DigiMeCore\/SyncError","title":"SyncError","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SyncError"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SyncError"}]}}}