{"identifier":{"url":"doc:\/\/me.digi.sdk.example.library.DigiMeSDK\/documentation\/DigiMeSDK\/Error-Handling","interfaceLanguage":"swift"},"sections":[],"kind":"article","metadata":{"modules":[{"name":"DigiMeSDK"}],"role":"article","title":"Error Handling","roleHeading":"Article"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"content":[{"type":"heading","level":2,"anchor":"Error-Types","text":"Error Types"},{"inlineContent":[{"type":"text","text":"All invocations of the SDK that can return some form of error will return an instance of "},{"type":"codeVoice","code":"SDKError"},{"type":"text","text":"."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"Some errors represent incorrect SDK setup while most represent server or runtime errors. These are described below with steps to rectify some of the common errors.","type":"text"}]},{"anchor":"SDK-Setup-Errors","level":3,"type":"heading","text":"SDK Setup Errors"},{"inlineContent":[{"type":"text","text":"These errors generally result from the misconfiguration of the SDK in some way, or other problems derived from the SDK’s implementation within your app. The error messages are designed to be self-explainatory, so not all will be covered here. This type of error will require address by the integrator of the SDK, due to being caused by an error on their part."}],"type":"paragraph"},{"level":5,"anchor":"SDKErrornoUrlScheme","text":"`SDKError.noUrlScheme`:","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"text":"Encountered","type":"text"}]},{"text":": If you do not set the right callback scheme in the ","type":"text"},{"type":"codeVoice","code":"Info.plist"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"strong","inlineContent":[{"text":"Resolution","type":"text"}]},{"type":"text","text":": Ensure you add "},{"type":"codeVoice","code":"CFBundleURLTypes"},{"text":" to your ","type":"text"},{"code":"Info.plist","type":"codeVoice"},{"type":"text","text":", see "},{"identifier":"https:\/\/github.com\/digime\/digime-sdk-ios\/blob\/master\/README.md","type":"reference","isActive":true},{"type":"text","text":" for details."}]},{"type":"heading","level":5,"text":"`SDKError.invalidPrivateOrPublicKey`:","anchor":"SDKErrorinvalidPrivateOrPublicKey"},{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Encountered"}]},{"type":"text","text":": When the private or public key given to "},{"code":"configuration","type":"codeVoice"},{"type":"text","text":" initializer is not of the correct format."},{"type":"text","text":" "},{"inlineContent":[{"type":"text","text":"Resolution"}],"type":"strong"},{"type":"text","text":": Ensure that the keys you specify are the full RSA private or public key including header and footer. i.e."}],"type":"paragraph"},{"syntax":"swift","code":["-----BEGIN RSA PRIVATE KEY----","{KEY CONTENT}","-----END RSA PRIVATE KEY-----"],"type":"codeListing"},{"level":3,"text":"Server Errors","anchor":"Server-Errors","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"When the digi.me service returns an error, this will generally be passed back as ","type":"text"},{"code":"SDKError.httpResponseError","type":"codeVoice"},{"type":"text","text":" or as "},{"code":"SDKError.urlRequestFailed","type":"codeVoice"},{"type":"text","text":", both containing the underlying error message. Some of the errors we handle internally within the SDK, retrying requests where appropriate. If, after exhausting this, we are unable to resolve the error, it will be passed onto you."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Some of the server errors are common enough that they have been mapped to specific SDKErrors, for example "},{"code":"SDKError.scopeOutOfBounds","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"SDKError.incorrectContractType"},{"type":"text","text":". These should only be encountered during SDK integration as they require programming changes to fix."}]},{"inlineContent":[{"text":"Most server side errors are short lived, so the recommended course of action is to try again a bit later, but in the case of a persisting error, please contact digi.me support.","type":"text"}],"type":"paragraph"},{"level":3,"text":"Other Runtime Errors","type":"heading","anchor":"Other-Runtime-Errors"},{"type":"paragraph","inlineContent":[{"text":"The remaining runtime errors generally fall into one of 2 camps - recoverable and unrecoverable","type":"text"}]},{"anchor":"Recoverable-Errors","type":"heading","text":"Recoverable Errors","level":4},{"type":"paragraph","inlineContent":[{"text":"The following are some of the most common recoverable errors:","type":"text"}]},{"anchor":"SDKErrorinvalidSession","level":5,"text":"`SDKError.invalidSession`:","type":"heading"},{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Encountered"}]},{"type":"text","text":": If you try to read data after a session has expired."},{"text":" ","type":"text"},{"type":"strong","inlineContent":[{"text":"Resolution","type":"text"}]},{"text":": Either explicitly call ","type":"text"},{"code":"DigiMe.requestDataQuery","type":"codeVoice"},{"text":" to obtain a new session or call ","type":"text"},{"type":"codeVoice","code":"DigiMe.readAllFiles"},{"text":" which implicitly obtains a new session.","type":"text"}],"type":"paragraph"},{"level":5,"type":"heading","text":"`SDKError.authorizationCancelled`:","anchor":"SDKErrorauthorizationCancelled"},{"inlineContent":[{"inlineContent":[{"type":"text","text":"Encountered"}],"type":"strong"},{"type":"text","text":": When user declines to grant their consent."},{"type":"text","text":" "},{"type":"strong","inlineContent":[{"text":"Resolution","type":"text"}]},{"text":": You may handle this in a way that’s appropriate to your app.","type":"text"}],"type":"paragraph"},{"anchor":"SDKErroralreadyReadingAllFiles","type":"heading","level":5,"text":"`SDKError.alreadyReadingAllFiles`:"},{"inlineContent":[{"inlineContent":[{"type":"text","text":"Encountered"}],"type":"strong"},{"text":": If multiple simultaneous calls to ","type":"text"},{"type":"codeVoice","code":"DigiMe.readAllFiles"},{"text":" are made. Only one call to this method is allowed at any time as it may trigger the server to refresh data from external sources.","type":"text"},{"text":" ","type":"text"},{"inlineContent":[{"type":"text","text":"Resolution"}],"type":"strong"},{"text":": If you need to make multiple calls, you should ensure that these calls are performed serially.","type":"text"}],"type":"paragraph"},{"anchor":"SDKErrorfileListPollingTimeout","type":"heading","text":"`SDKError.fileListPollingTimeout`:","level":5},{"type":"paragraph","inlineContent":[{"inlineContent":[{"type":"text","text":"Encountered"}],"type":"strong"},{"text":": This typically appears in the completion block of ","type":"text"},{"type":"codeVoice","code":"DigiMe.readAllFiles"},{"type":"text","text":" and indicates that the SDK has made multiple calls to retrieve file list with there being no changes to contents of file list. This is usually due to the server running a synchronization between service and user’s digi.me which is taking too long (denoted by "},{"type":"codeVoice","code":"FileList.status.state"},{"text":" not completing in a timely manner).","type":"text"},{"type":"text","text":" "},{"inlineContent":[{"text":"Resolution","type":"text"}],"type":"strong"},{"type":"text","text":": Make a subsequent call to "},{"type":"codeVoice","code":"DigiMe.readAllFiles"},{"text":" at a later date to see if the synchronization finishes.","type":"text"}]},{"anchor":"Unrecoverable-Errors","text":"Unrecoverable Errors","type":"heading","level":4},{"inlineContent":[{"text":"There are some errors which should never be encountered, which indicate a failure of the SDK. If encountered, please contact digi.me support.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"In particular, these are "},{"type":"codeVoice","code":"SDKError.writeRequestFailure"},{"type":"text","text":", "},{"type":"codeVoice","code":"SDKError.invalidData"},{"text":", and ","type":"text"},{"type":"codeVoice","code":"SDKError.invalidWriteMetadata"},{"type":"text","text":"."}],"type":"paragraph"},{"level":2,"text":"Further Issues","anchor":"Further-Issues","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If, after reading this section, your issue persists, please contact digi.me developer support. The easiest way to do this is via our "},{"identifier":"https:\/\/developers.digi.me\/slack\/join","isActive":true,"type":"reference"},{"type":"text","text":". Here you can speak directly with other developers working with us, as well as digi.me’s own development team."}]}],"kind":"content"}],"abstract":[{"type":"text","text":"Whilst using the SDK, you may encounter a number of errors. Some of these, we will attempt to recover from on your behalf, however, there are a large number that will require you to take some kind of action."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/digimesdk\/error-handling"]}],"hierarchy":{"paths":[["doc:\/\/me.digi.sdk.example.library.DigiMeSDK\/documentation\/DigiMeSDK"]]},"references":{"https://developers.digi.me/slack/join":{"title":"Slack Workspace","identifier":"https:\/\/developers.digi.me\/slack\/join","type":"link","titleInlineContent":[{"type":"text","text":"Slack Workspace"}],"url":"https:\/\/developers.digi.me\/slack\/join"},"doc://me.digi.sdk.example.library.DigiMeSDK/documentation/DigiMeSDK":{"url":"\/documentation\/digimesdk","abstract":[{"text":"Digi.me - The Private Sharing Platform","type":"text"}],"type":"topic","title":"DigiMeSDK","kind":"symbol","identifier":"doc:\/\/me.digi.sdk.example.library.DigiMeSDK\/documentation\/DigiMeSDK","role":"collection"},"https://github.com/digime/digime-sdk-ios/blob/master/README.md":{"titleInlineContent":[{"type":"text","text":"README"}],"type":"link","title":"README","identifier":"https:\/\/github.com\/digime\/digime-sdk-ios\/blob\/master\/README.md","url":"https:\/\/github.com\/digime\/digime-sdk-ios\/blob\/master\/README.md"}}}