{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/digimecore\/syncerror\/code"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"code","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError\/code"},"metadata":{"symbolKind":"property","roleHeading":"Instance Property","title":"code","modules":[{"name":"DigiMeCore"}],"externalID":"s:10DigiMeCore9SyncErrorV4codeSSvp","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"code"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore","doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError"]]},"sections":[],"references":{"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore/SyncError/code":{"title":"code","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"code","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/digimecore\/syncerror\/code","kind":"symbol","identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError\/code"},"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore/SyncError":{"type":"topic","title":"SyncError","role":"symbol","url":"\/documentation\/digimecore\/syncerror","abstract":[{"text":"Reason why connecting to source or importing data from source into userâ€™s library failed","type":"text"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SyncError","kind":"identifier"}],"navigatorTitle":[{"text":"SyncError","kind":"identifier"}],"identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore\/SyncError"},"doc://me.digi.sdk.example.librarycore.DigiMeCore/documentation/DigiMeCore":{"title":"DigiMeCore","url":"\/documentation\/digimecore","type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/me.digi.sdk.example.librarycore.DigiMeCore\/documentation\/DigiMeCore","abstract":[]}}}